DIAMOND_DEPTH = 10
print("; configuration")
print("""(set-option :print-success false)
(set-option :AUTO_CONFIG false)
(set-option :pp.bv_literals false)
(set-option :MODEL.V2 true)
(set-option :smt.PHASE_SELECTION 0)
(set-option :smt.RESTART_STRATEGY 0)
(set-option :smt.RESTART_FACTOR |1.5|)
(set-option :smt.ARITH.RANDOM_INITIAL_VALUE true)
(set-option :smt.CASE_SPLIT 3)
(set-option :smt.DELAY_UNITS true)
(set-option :NNF.SK_HACK true)
(set-option :smt.MBQI false)
(set-option :TYPE_CHECK true)
(set-option :smt.BV.REFLECT true)

(declare-fun f(Int) Int)
(declare-fun g(Int) Int)
(declare-fun h(Int) Int)
""")

print("; diamond")
for i in range(DIAMOND_DEPTH):
    print("(assert (or")
    print(f"\t(and (<= (f {i}) (g {i})) (<= (g {i}) (f {i+1})))")
    print(f"\t(and (<= (f {i}) (h {i})) (<= (h {i}) (f {i+1})))")
    print(f"))")
print("")
print(f"(assert (< (f {DIAMOND_DEPTH}) (f 0)))")
print("")

print("; pruning quantifiers")
print("""(assert (forall ((x Int))
    (!
        (=> (<= (g x) (f (+ x 1)))
            (not (<= (h (+ x 1)) (f (+ x 2))))
        )
        :pattern ((g x))
    )
))
""")
print("""(assert (forall ((x Int))
    (!
        (=> (<= (h x) (f (+ x 1)))
            (not (<= (g (+ x 1)) (f (+ x 2))))
        )
        :pattern ((h x))
    )
))
""")
print(f"(check-sat)")

